name: tripnote
description: "여행 계획 및 일정 관리 앱"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  dio: ^4.0.6

  flutter_dotenv: ^6.0.0

  flutter_secure_storage: ^8.0.0

  kakao_flutter_sdk_user: ^1.4.2
  google_sign_in: ^7.2.0

  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  intl: ^0.20.2
  url_launcher: ^6.1.10
  
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/
    - assets/icons/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
